name: gojek_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/food_1.jpg
  - assets/images/food_2.jpg
  - assets/images/food_3.jpg
  - assets/images/food_4.jpg
  - assets/images/food_5.jpg
  - assets/images/promo_1.jpg
  - assets/images/promo_2.jpg
  - assets/images/promo_3.jpg
  - assets/images/promo_4.jpg
  - assets/icons/icon_menu.png
  - assets/icons/icon_saldo.png
  - assets/icons/icon_scan.png
  - assets/icons/icon_transfer.png
  - assets/img_gojek_logo.png
  fonts:
    - family: NeoSans
      fonts: 
      - asset: assets/fonts/Neo Sans Std Regular.otf
    - family: NeoSansBold
      fonts: 
      - asset: assets/fonts/Neo Sans Std Bold.otf
