name: gojek_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

  # flutter:
  #   uses-material-design: true
  #   public:
  #     - public/image/food_1.jpg
  #     - assets/image/food_2.jpg
  #     - assets/image/food_3.jpg
  #     - assets/image/food_4.jpg
  #     - assets/image/food_5.jpg
  #     - assets/image/promo_1.jpg
  #     - assets/image/promo_2.jpg
  #     - assets/image/promo_3.jpg
  #     - assets/image/promo_4.jpg
  #     - assets/image/icon_menu.png
  #     - assets/image/icon_saldo.png
  #     - assets/image/icon_scan.png
  #     - assets/image/icon_transfer.png
  #     - assets/image/gojek_logo.png
  font:
    - family: NeoSans
      font:
        - public: public/font/Neo Sans Std Regular.otf
    - family: NeoSans
      font:
        - public: assets/fonts/Neo Sans Std Bold.otf
